name: Build and Release

on:
  push:
    tags:
      - "V*"


permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4.2.0

      - name: Install dependencies
        run: npm ci

      - name: Build and Package App
        run: npm run make

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4.6.0
        with:
          name: electron-forge-build-${{ matrix.os }}
          path: | 
            out/make/dmg/*

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            out/make/dmg/*